
# 屏幕宽高常量
SCREEN_WIDTH , SCREEN_HEIGHT = 800, 600
SCREEN_SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)
GROUND_HEIGHT = SCREEN_HEIGHT - 62

# 背景图缩放比例
BG_MULTI = 2.68
PLAYER_MULTI = 2.9
BRICK_MULTI = 2.69

#设置字体
FONT = 'FixedSys.ttf'


GRAVITY = 0.3